apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: player-data-api
  newName: docker.io/lanrell/player-data-api
  newTag: v1.0.0-2-g275a4b6
